title: Tanagra Space
author: tanagraspace.com
email: tanagra@subspacesignal.com
description: Bringing AI into orbit and making it accessible.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tanagraspace.com" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

